name: Python App CI

on:
  push:
    branches: [",master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: |
          pytest --junitxml=results.xml

      - name: Build with PyInstaller
        run: |
          pip install pyinstaller
          pyinstaller --onefile add2vals

      - name: Upload executable artifact
        uses: actions/upload-artifact@v3
        with:
          name: add2vals-executable
          path: dist/add2vals
